services:
  frontend:
    container_name: web-app
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - "${WEB_APP_PORT}:${WEB_APP_PORT}"
    volumes:
      - ./web-app:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
    depends_on:
      - backend
    networks:
      - avyro_network
    restart: unless-stopped

  backend:
    container_name: web-api
    build:
      context: ./web-api
      dockerfile: Dockerfile
    ports:
      - "${WEB_API_PORT}:${WEB_API_PORT}"
    volumes:
      - ./web-api:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - mongo
    networks:
      - avyro_network
    restart: unless-stopped

  mongo:
    container_name: mongo-db
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - avyro_network
    restart: unless-stopped

  mongo-express:
    container_name: mongo-admin
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    depends_on:
      - mongo
    networks:
      - avyro_network
    restart: unless-stopped

networks:
  avyro_network:
    driver: bridge

volumes:
  mongo_data:
